// Code generated by command: go run asm.go -out bytes.s -stubs bytes.go. DO NOT EDIT.

package search

// findInChunk is only generated for testing.
func findInChunk(needle []byte, haystack []byte) int64

// indexAvx512 returns the first position the needle is in the haystack.
func indexAvx512(haystack []byte, needle []byte) int64
