// Code generated by command: go run asm_avx2.go -out bytes_avx2_amd64.s -stubs bytes_avx2_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func findInChunk(needle []byte, haystack []byte) int64
// Requires: AVX, AVX2, BMI
TEXT ·findInChunk(SB), NOSPLIT, $0-56
	MOVQ haystack_base+24(FP), AX
	MOVQ needle_len+8(FP), CX
	MOVQ needle_base+0(FP), DX
	MOVQ $+0, BX
	MOVQ CX, SI
	DECQ SI

	// create vector filled with the byte at idx1, and another for idx2
	LEAQ         (DX)(BX*1), DI
	LEAQ         (DX)(SI*1), R8
	VPBROADCASTB (DI), Y0
	VPBROADCASTB (R8), Y1

	// begin test find in chunk
	LEAQ     (AX)(BX*1), BX
	LEAQ     (AX)(SI*1), SI
	VMOVDQU  (BX), Y2
	VMOVDQU  (SI), Y3
	VPCMPEQB Y0, Y2, Y0
	VPCMPEQB Y1, Y3, Y1
	VPAND    Y0, Y1, Y0

	// calculate offsets
	VPMOVMSKB Y0, BX
	MOVQ      $-1, SI

	// loop over offsets, ie bit positions
test_offsets_loop:
	CMPL   BX, $0x00
	JE     test_offsets_loop_done
	TZCNTL BX, SI

	// candidate match start = curPtr + bit position
	LEAQ (AX)(SI*1), DI

	// test chunk (full needle)
	// compare two slices
	MOVQ CX, R8
	CMPQ CX, $0x04
	JGE  test_compare_four_bytes

	// compare two slices one byte at a time
	MOVQ DX, R9

test_memcmp_one_loop:
	// loop by one byte
	CMPQ R8, $0x00
	JE   test_memcmp_one_loop_done
	MOVB (R9), R10
	CMPB (DI), R10
	JNE  test_memcmp_one_loop_done
	ADDQ $0x01, DI
	ADDQ $0x01, R9
	DECQ R8
	JMP  test_memcmp_one_loop

test_memcmp_one_loop_done:
	JMP test_memcmp_done

test_compare_four_bytes:
	// compare two slices four bytes at a time
	MOVQ DI, R9
	MOVQ DX, R10
	LEAQ -4(DI)(CX*1), DI
	LEAQ -4(DX)(CX*1), R11

	// loop by four bytes
test_memcmp_four_loop:
	CMPQ R9, DI
	JGE  test_memcmp_four_loop_done
	MOVL (R10), R12
	CMPL (R9), R12
	JNE  test_memcmp_four_done
	ADDQ $0x04, R9
	ADDQ $0x04, R10
	JMP  test_memcmp_four_loop

test_memcmp_four_loop_done:
	// compare last four bytes
	MOVL (R11), R12
	CMPL (DI), R12
	JNE  test_memcmp_four_done
	XORQ R8, R8

test_memcmp_four_done:
test_memcmp_done:
	// break early on a match
	CMPQ R8, $0x00
	JE   test_chunk_match
	MOVL BX, SI
	DECL SI
	ANDL SI, BX
	JMP  test_offsets_loop

test_offsets_loop_done:
	MOVQ $-1, SI

test_chunk_match:
	// end test find in chunk
	MOVQ SI, ret+48(FP)
	VZEROUPPER
	RET

// func indexAvx2(haystack []byte, needle []byte, idx1 int, idx2 int) int64
// Requires: AVX, AVX2, BMI
TEXT ·indexAvx2(SB), NOSPLIT, $8-72
	MOVQ needle_base+24(FP), AX
	MOVQ needle_len+32(FP), CX
	MOVQ idx1+48(FP), DX
	MOVQ idx2+56(FP), BX
	MOVQ haystack_base+0(FP), SI
	MOVQ SI, DI
	ADDQ haystack_len+8(FP), DI
	SUBQ $0x20, DI
	SUBQ CX, DI
	ADDQ $0x01, DI
	MOVQ SI, R8

	// create vector filled with the byte at idx1, and another for idx2
	LEAQ         (AX)(DX*1), R9
	LEAQ         (AX)(BX*1), R10
	VPBROADCASTB (R9), Y0
	VPBROADCASTB (R10), Y1

chunk_loop:
	// begin main find in chunk
	LEAQ     (R8)(DX*1), R9
	LEAQ     (R8)(BX*1), R10
	VMOVDQU  (R9), Y2
	VMOVDQU  (R10), Y3
	VPCMPEQB Y0, Y2, Y2
	VPCMPEQB Y1, Y3, Y3
	VPAND    Y2, Y3, Y2

	// calculate offsets
	VPMOVMSKB Y2, R9
	MOVQ      $-1, R10

	// loop over offsets, ie bit positions
main_offsets_loop:
	CMPL   R9, $0x00
	JE     main_offsets_loop_done
	TZCNTL R9, R10

	// candidate match start = curPtr + bit position
	LEAQ (R8)(R10*1), R11

	// test chunk (full needle)
	// compare two slices
	MOVQ CX, R12
	CMPQ CX, $0x04
	JGE  main_compare_four_bytes

	// compare two slices one byte at a time
	MOVQ AX, R13

main_memcmp_one_loop:
	// loop by one byte
	CMPQ R12, $0x00
	JE   main_memcmp_one_loop_done
	MOVB (R13), R14
	CMPB (R11), R14
	JNE  main_memcmp_one_loop_done
	ADDQ $0x01, R11
	ADDQ $0x01, R13
	DECQ R12
	JMP  main_memcmp_one_loop

main_memcmp_one_loop_done:
	JMP main_memcmp_done

main_compare_four_bytes:
	// compare two slices four bytes at a time
	MOVQ R11, R13
	MOVQ AX, R14
	LEAQ -4(R11)(CX*1), R11
	LEAQ -4(AX)(CX*1), R15

	// loop by four bytes
main_memcmp_four_loop:
	CMPQ R13, R11
	JGE  main_memcmp_four_loop_done
	MOVL (R14), BP
	CMPL (R13), BP
	JNE  main_memcmp_four_done
	ADDQ $0x04, R13
	ADDQ $0x04, R14
	JMP  main_memcmp_four_loop

main_memcmp_four_loop_done:
	// compare last four bytes
	MOVL (R15), BP
	CMPL (R11), BP
	JNE  main_memcmp_four_done
	XORQ R12, R12

main_memcmp_four_done:
main_memcmp_done:
	// break early on a match
	CMPQ R12, $0x00
	JE   main_chunk_match
	MOVL R9, R10
	DECL R10
	ANDL R10, R9
	JMP  main_offsets_loop

main_offsets_loop_done:
	MOVQ $-1, R10

main_chunk_match:
	// end main find in chunk
	// break early when offset is >=0.
	CMPQ R10, $0x00
	JGE  matched

	// if curPtr == maxPtr we just scanned the final window
	CMPQ R8, DI
	JGE  not_matched

	// advance curPtr by LOOP_SIZE_AVX2, clamped to maxPtr
	ADDQ $0x20, R8
	CMPQ R8, DI
	JLE  chunk_loop
	MOVQ DI, R8
	JMP  chunk_loop

matched:
	// adjust the offset and return the true index
	MOVQ R8, AX
	SUBQ SI, AX
	ADDQ R10, AX
	MOVQ AX, ret+64(FP)
	VZEROUPPER
	RET

not_matched:
	MOVQ R10, ret+64(FP)
	VZEROUPPER
	RET
