// Code generated by command: go run asm_avx2.go -out bytes_avx2_amd64.s -stubs bytes_avx2_amd64.go. DO NOT EDIT.

package search

// findInChunk is only generated for testing.
func findInChunk(needle []byte, haystack []byte) int64

// indexAvx2 returns the first position the needle is in the haystack. The caller must ensure len(needle) >= 1 and len(haystack) >= LOOP_SIZE_AVX2 + len(needle) - 1.
func indexAvx2(haystack []byte, needle []byte) int64
