// Code generated by command: go run asm.go -out bytes.s -stubs bytes.go. DO NOT EDIT.

package search

func Mask(needle []byte, haystack []byte) bool

// Search checks if haystack contains needle.
func Search(haystack []byte, needle []byte) bool
