// Code generated by command: go run asm_avx2.go -out bytes_avx2_amd64.s -stubs bytes_avx2_amd64.go. DO NOT EDIT.

#include "textflag.h"

// func findInChunk(needle []byte, haystack []byte) int64
// Requires: AVX, AVX2, BMI
TEXT ·findInChunk(SB), NOSPLIT, $0-56
	MOVQ haystack_base+24(FP), AX
	MOVQ needle_len+8(FP), CX
	DECQ CX
	MOVQ needle_base+0(FP), DX

	// create vector filled with first and last character
	MOVQ         DX, BX
	ADDQ         CX, BX
	VPBROADCASTB (DX), Y0
	VPBROADCASTB (BX), Y1

	// begin test find in chunk
	MOVQ     AX, BX
	ADDQ     CX, BX
	VMOVDQU  (AX), Y2
	VMOVDQU  (BX), Y3
	VPCMPEQB Y0, Y2, Y0
	VPCMPEQB Y1, Y3, Y1
	VPAND    Y0, Y1, Y0

	// calculate offsets
	VPMOVMSKB Y0, BX
	MOVQ      $-1, SI

	// loop over offsets, ie bit positions
test_offsets_loop:
	CMPL   BX, $0x00
	JE     test_offsets_loop_done
	TZCNTL BX, SI
	MOVQ   AX, DI
	ADDQ   SI, DI

	// test chunk
	// compare two slices
	MOVQ CX, R8
	CMPQ CX, $0x04
	JGE  test_compare_four_bytes

	// compare two slices one byte at a time
	MOVQ DX, R9

test_memcmp_one_loop:
	// loop by one byte
	CMPQ R8, $0x00
	JE   test_memcmp_one_loop_done
	MOVB (R9), R10
	CMPB (DI), R10
	JNE  test_memcmp_one_loop_done
	ADDQ $0x01, DI
	ADDQ $0x01, R9
	DECQ R8
	JMP  test_memcmp_one_loop

test_memcmp_one_loop_done:
	JMP test_memcmp_done

test_compare_four_bytes:
	// compare two slices four bytes at a time
	MOVQ DI, R9
	MOVQ DX, R10
	ADDQ CX, DI
	SUBQ $0x04, DI
	MOVQ DX, R11
	ADDQ CX, R11
	SUBQ $0x04, R11

	// loop by four bytes
test_memcmp_four_loop:
	CMPQ R9, DI
	JGE  test_memcmp_four_loop_done
	MOVL (R10), R12
	CMPL (R9), R12
	JNE  test_memcmp_four_done
	ADDQ $0x04, R9
	ADDQ $0x04, R10
	JMP  test_memcmp_four_loop

test_memcmp_four_loop_done:
	// compare last four bytes
	MOVL (R11), R12
	CMPL (DI), R12
	JNE  test_memcmp_four_done
	XORQ R8, R8

test_memcmp_four_done:
test_memcmp_done:
	// break early on a match
	CMPQ R8, $0x00
	JE   test_chunk_match
	MOVL BX, SI
	DECL SI
	ANDL SI, BX
	JMP  test_offsets_loop

test_offsets_loop_done:
	MOVQ $-1, SI

test_chunk_match:
	// end test find in chunk
	MOVQ SI, ret+48(FP)
	RET

// func indexAvx2(haystack []byte, needle []byte) int64
// Requires: AVX, AVX2, BMI
TEXT ·indexAvx2(SB), NOSPLIT, $0-56
	MOVQ needle_base+24(FP), AX
	MOVQ needle_len+32(FP), CX
	DECQ CX
	MOVQ haystack_base+0(FP), DX
	MOVQ DX, BX
	ADDQ haystack_len+8(FP), BX
	SUBQ $0x20, BX
	SUBQ CX, BX
	MOVQ DX, SI

	// create vector filled with first and last character
	MOVQ         AX, DI
	ADDQ         CX, DI
	VPBROADCASTB (AX), Y0
	VPBROADCASTB (DI), Y1

chunk_loop:
	// begin main find in chunk
	MOVQ     SI, DI
	ADDQ     CX, DI
	VMOVDQU  (SI), Y2
	VMOVDQU  (DI), Y3
	VPCMPEQB Y0, Y2, Y2
	VPCMPEQB Y1, Y3, Y3
	VPAND    Y2, Y3, Y2

	// calculate offsets
	VPMOVMSKB Y2, DI
	MOVQ      $-1, R8

	// loop over offsets, ie bit positions
main_offsets_loop:
	CMPL   DI, $0x00
	JE     main_offsets_loop_done
	TZCNTL DI, R8
	MOVQ   SI, R9
	ADDQ   R8, R9

	// test chunk
	// compare two slices
	MOVQ CX, R10
	CMPQ CX, $0x04
	JGE  main_compare_four_bytes

	// compare two slices one byte at a time
	MOVQ AX, R11

main_memcmp_one_loop:
	// loop by one byte
	CMPQ R10, $0x00
	JE   main_memcmp_one_loop_done
	MOVB (R11), R12
	CMPB (R9), R12
	JNE  main_memcmp_one_loop_done
	ADDQ $0x01, R9
	ADDQ $0x01, R11
	DECQ R10
	JMP  main_memcmp_one_loop

main_memcmp_one_loop_done:
	JMP main_memcmp_done

main_compare_four_bytes:
	// compare two slices four bytes at a time
	MOVQ R9, R11
	MOVQ AX, R12
	ADDQ CX, R9
	SUBQ $0x04, R9
	MOVQ AX, R13
	ADDQ CX, R13
	SUBQ $0x04, R13

	// loop by four bytes
main_memcmp_four_loop:
	CMPQ R11, R9
	JGE  main_memcmp_four_loop_done
	MOVL (R12), R14
	CMPL (R11), R14
	JNE  main_memcmp_four_done
	ADDQ $0x04, R11
	ADDQ $0x04, R12
	JMP  main_memcmp_four_loop

main_memcmp_four_loop_done:
	// compare last four bytes
	MOVL (R13), R14
	CMPL (R9), R14
	JNE  main_memcmp_four_done
	XORQ R10, R10

main_memcmp_four_done:
main_memcmp_done:
	// break early on a match
	CMPQ R10, $0x00
	JE   main_chunk_match
	MOVL DI, R8
	DECL R8
	ANDL R8, DI
	JMP  main_offsets_loop

main_offsets_loop_done:
	MOVQ $-1, R8

main_chunk_match:
	// end main find in chunk
	// break early when offset is >=0.
	CMPQ R8, $0x00
	JGE  matched

	// if curPtr == maxPtr we just scanned the final window
	CMPQ SI, BX
	JGE  not_matched

	// advance curPtr by LOOP_SIZE_AVX2, clamped to maxPtr
	ADDQ $0x20, SI
	CMPQ SI, BX
	JLE  chunk_loop
	MOVQ BX, SI
	JMP  chunk_loop

matched:
	// adjust the offset and return the true index
	MOVQ SI, AX
	SUBQ DX, AX
	ADDQ R8, AX
	MOVQ AX, ret+48(FP)
	RET

not_matched:
	MOVQ R8, ret+48(FP)
	RET
