// Code generated by command: go run asm.go -out genericsimd.s -stubs genericsimd.go. DO NOT EDIT.

package simd

// findInChunk is only generated for testing.
func findInChunk(needle []byte, haystack []byte) int64

// Index returns the first position the needle is in the haystack.
func Index(haystack []byte, needle []byte) int64
