name: Go package

on: [push]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.24'
          cache: false
      - uses: actions/checkout@v3

      - name: Lint 
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.4.0
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-13]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.24'

      - name: Generate 
        run: |
          go generate -v ./...
          git diff --exit-code || (echo "Please generate assembly by running 'go generate ./...'" && false)

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
